// <auto-generated />
using Company_Management_Panel_CSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_Management_Panel_CSharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251006151530_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LogoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "info@techcorp.com",
                            LogoPath = "placeholder.png",
                            Name = "Tech Corp",
                            Website = "https://techcorp.com"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@healthinc.com",
                            LogoPath = "placeholder.png",
                            Name = "Health Inc",
                            Website = "https://healthinc.com"
                        });
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "alice@techcorp.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "07775845772"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Email = "bob@techcorp.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            PhoneNumber = "07830018563"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Email = "carol@healthinc.com",
                            FirstName = "Carol",
                            LastName = "Davis",
                            PhoneNumber = "07774750114"
                        });
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Employee", b =>
                {
                    b.HasOne("Company_Management_Panel_CSharp.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
