// <auto-generated />
using Company_Management_Panel_CSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_Management_Panel_CSharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010121404_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "info@techcorp.com",
                            Name = "Tech Corp",
                            Website = "https://techcorp.com"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@healthinc.com",
                            Name = "Health Inc",
                            Website = "https://healthinc.com"
                        });
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "alice@techcorp.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "07775845772"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Email = "bob@techcorp.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            PhoneNumber = "07830018563"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Email = "daniel@techcorp.com",
                            FirstName = "Daniel",
                            LastName = "Wright",
                            PhoneNumber = "07765123987"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            Email = "ella@techcorp.com",
                            FirstName = "Ella",
                            LastName = "Brown",
                            PhoneNumber = "07798104563"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            Email = "frank@techcorp.com",
                            FirstName = "Frank",
                            LastName = "Thompson",
                            PhoneNumber = "07819245670"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            Email = "grace@techcorp.com",
                            FirstName = "Grace",
                            LastName = "Anderson",
                            PhoneNumber = "07770135842"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 1,
                            Email = "harry@techcorp.com",
                            FirstName = "Harry",
                            LastName = "Lewis",
                            PhoneNumber = "07804329871"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 1,
                            Email = "isla@techcorp.com",
                            FirstName = "Isla",
                            LastName = "Turner",
                            PhoneNumber = "07766129854"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 2,
                            Email = "carol@healthinc.com",
                            FirstName = "Carol",
                            LastName = "Davis",
                            PhoneNumber = "07774750114"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 2,
                            Email = "jack@healthinc.com",
                            FirstName = "Jack",
                            LastName = "Miller",
                            PhoneNumber = "07801563472"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 2,
                            Email = "katie@healthinc.com",
                            FirstName = "Katie",
                            LastName = "Wilson",
                            PhoneNumber = "07894216053"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 2,
                            Email = "liam@healthinc.com",
                            FirstName = "Liam",
                            LastName = "Moore",
                            PhoneNumber = "07787520169"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 2,
                            Email = "mia@healthinc.com",
                            FirstName = "Mia",
                            LastName = "Taylor",
                            PhoneNumber = "07831654729"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 2,
                            Email = "noah@healthinc.com",
                            FirstName = "Noah",
                            LastName = "Clark",
                            PhoneNumber = "07790765231"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 2,
                            Email = "olivia@healthinc.com",
                            FirstName = "Olivia",
                            LastName = "Martin",
                            PhoneNumber = "07762594318"
                        });
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Employee", b =>
                {
                    b.HasOne("Company_Management_Panel_CSharp.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Company_Management_Panel_CSharp.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
